#!/bin/bash
S3_BUCKET=$1
S3_FILE_NAME=$2

echo "Checking for s3 file..."
echo -e "  bucket  $S3_BUCKET"
echo -e "  file    $S3_FILE_NAME"
echo ""

S3_BUCKET_FILES=`aws s3 ls "s3://$S3_BUCKET"`

FILE_FOUND=false

while read -r line; do
    read -a line_sep <<< "${line}"

    if [ ${line_sep[3]} == $S3_FILE_NAME ]
    then
      FILE_FOUND=true
    fi
done <<< "$S3_BUCKET_FILES"

if $FILE_FOUND
then
  echo "file found"
  exit 0
else
  echo "file not found"
  exit 1
fi
